### ISSUE TITLE
Another Unknown i2c device here: Reg: 0x75 Value:0x75 Reg: 0x00 Value:0xC4

### ISSUE THREAD

**Issue by CaiVR** [Levi--G/IMU-WhoAmIVerifier#3]
```
 [ERR] Found unknown I2C device on address 0x68 with possible id's:
 Reg: 0x75 Value:0x75
 Reg: 0x00 Value:0xC4
```
Am using what is supposedly an MPU9250 (seen below), and it looks to me like its legit. 
![Unrecognised 9250](https://user-images.githubusercontent.com/98002096/171231171-e390b530-a715-4cb0-a3cf-4dd4c4e41f74.jpg)
All I'm looking for is confirmation whether this is the genuine chip on the board, and how to force slimeVR to recognise this so I can attempt to get it to work under the MPU9250 integration.
Cheers for your time :)

**Comment by Levi--G** [comment]
If i had to take a guess i would say this is most likely not a genuine chip, it would have been detected as such. However that doesn't mean it won't work, you will just need to try that. Better to ask help in the slimevr discord for the exact code change, its been a while since i worked on that. Also don't forget to solder your Gnd wire ;)
Have fun!

**Comment by Levi--G** [comment]
Closing as answered
